### PR TITLE
This solves issue #75

### PR DESCRIPTION
**Pull request by Edo78**

### CODE REVIEW

**Comment by tomchentw** [comment]
@Edo78 Thanks for looking into this. Could you try explaining why this would help? I thought they were identical.

**Comment by Edo78** [comment]
I'll do my best but I'm not a react expert.
Mainly I got the warning and after this patch I doesn't get it anymore ;)
To be a little more serious I've tried to follow the guidelines here https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by tomchentw** [comment]
Thanks @Edo78 for the reply. As I mentioned in #75, I really don't get the error when running **this** repo with `npm start`. Could you show me some screenshots of your terminal/console of the warnings? Which version of the React are you using?

Thanks!

**Comment by Edo78** [comment]
I'm using react 15.3.2 and using react-toastr 2.8.1 I got the warning in the chrome console
schermata 2016-10-12 alle 11 32 41

**Comment by tomchentw** [comment]
@Edo78 Sorry, I cannot really reproduce this error on my computer. Would you be able to create a minimal repo and share it with us?

**Comment by Edo78** [comment]
I'll give a try as soon as possible (don't hold your breath in the meanwhile :D )

**Comment by adamduren** [comment]
@tomchentw [This](https://facebook.github.io/react/warnings/dont-call-proptypes.html) explains the need for this. In summary:

> Note: React.PropTypes is deprecated as of React v15.5. Please use the prop-types library instead.

**Comment by tomchentw** [comment]
I'm aware of the new `prop-types` package, but I don't see why the error is coming: 
> @Edo78 schermata 2016-10-12 alle 11 32 41

Can't repro. Close now.

**Pull request closed without merging**
