### PR TITLE
fixed 「ERROR in Cannot find module 'object-assign'   @ ./styles/index.scss 4:14-116 13:2-17:4 14:20-122」

### PR DESCRIPTION
**Pull request by roth1002**

### CODE REVIEW

**Comment by jerairrest** [comment]
instead of adding another dependancy could you just use the babel-core polyfill? (babel-core is already a dependancy of this package.)

```
import 'babel-core/polyfill';
```

**Comment by roth1002** [comment]
:+1:

**Comment by tomchentw** [comment]
I just did a fresh clone and `npm install` and I'm not getting this issue.  Any ideas?

**Comment by jerairrest** [comment]
I'm not sure if this PR is needed if you use the babel-core/polyfill in your project.

**Comment by tomchentw** [comment]
@jerairrest Did you mean in `react-toastr` or in a client app like `examples/gh-pages`?

**Comment by jerairrest** [comment]
I mean in a client app. I've also pulled the latest and I'm not getting this error as well.

**Comment by tomchentw** [comment]
Got it. Thanks @jerairrest !

**Pull request closed without merging**
