### PR TITLE
Fixes #63 : Do not propagate component specific props to div

### LINKED ISSUE #63: warning about unknown props
By just mounting the container on react 15.2.0:

```javascript
Warning: Unknown props `toastMessageFactory`, `toastType`, `preventDuplicates`, `newestOnTop` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by ToastContainer)
    in ToastContainer (created by Toastr)
    in Toastr (created by App)
```

### PR DESCRIPTION
**Pull request by abalhier**
See issue https://github.com/Hacker0x01/react-datepicker/issues/517 and Dan Abramov (gaearon) comments

### CODE REVIEW

**Comment by abalhier** [comment]
I used pick in my first version of the pull request. But by using lodash omit, it allows to propagate className and style and other props which maybe supported by a div.

**Comment by tomchentw** [comment]
@abalhier thanks! This looks great. Just one more thing: could you revert your changes of `lib` folder in this branch? They should be automatically generated by the release script, thanks!

**Comment by abalhier** [comment]
Done ! :)

**Comment by tomchentw** [comment]
Released [v2.8.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.8.0)

**Pull request merged**
