### PR TITLE
refactor: update dependencies & fix deprecated for React 16

### LINKED ISSUE #86: React 15.4.0 is not supporting import `react/lib/*`
React 15.4.0 is not supporting import `react/lib/*` or `react-dom/lib/*` anymore.

React package and browser build no longer "secretly" includes React DOM.
Release wiki: https://github.com/facebook/react/releases/tag/v15.4.0
Dan Abramov tweet: https://twitter.com/dan_abramov/status/798926305030877184

Please review the code in the `animationMixin.js`
`animationMixin.js`: https://github.com/tomchentw/react-toastr/blob/b0fadc4afd51d381b983ce499d6cdfb667d319d2/lib/ToastMessage/animationMixin.js#L7

### LINKED ISSUE #94: Accessing PropTypes via the main React package is deprecated
I opened a pull request to fix this error: https://github.com/tomchentw/react-toastr/pull/93

image

### LINKED ISSUE #95: React.createClass is deprecated
This is throwing errors in this library. There seems to be two instances of it in your code.

image

### PR DESCRIPTION
**Pull request by KagamiChan**
to make react-toastr compatible with future React 16:
- updated React to 15.6.1
- removed react-addons-test-utils since it is deprecated in favor of
react-dom/test-utils and react-test-renderer
- removed react-addons-update since it is deprecated in favor of
immutability-helper
- added create-react-class to replace React.createClass
- added prop-types since React will no longer ships with it
- created transitionEvents.js to provide transition event
compatibility

Have to say that this version of transitionEvents.js borrows many ideas from Facebook's original codes, don't know whether I should place a license in it

fixes #95 
fixes #94 
fixes #86

### CODE REVIEW

**Comment by KagamiChan** [comment]
pinging @tomchentw

**Comment by tomchentw** [comment]
I'll land #109 first, and look into what you've done for #86 later. Thanks

**Comment by tomchentw** [comment]
Released [v2.9.1](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.1)

**Comment by KagamiChan** [comment]
Good job, thank you

**Pull request closed without merging**
