### PR TITLE
feat(preventDuplicates): Changed to list

### PR DESCRIPTION
**Pull request by RangarajKaushikSundar**
The prevent duplicates feature works by checking the previously rendered message with the current message and avoids duplicates. There is a test case which will not pass in the following situation - success('hello') _--- followed by -->_ success('bye') _--- followed by-->_ success('hello'). The last "hello" should not render until the previous "hello" has unmounted.

Now, the code maintains a list of messages that are currently being rendered. This makes sure that aforementioned issue doesn't happen.

### CODE REVIEW

**Comment by RangarajKaushikSundar** [comment]
@tomchentw The previous pull request helps us avoid the duplicate messages. Kindly approve this pull request since it completes the functionality.

**Comment by tomchentw** [comment]
@RangarajKaushikSundar I'd like to invite you to be a collaborator of this project. Are you interested?

**Comment by RangarajKaushikSundar** [comment]
@tomchentw I would be happy to.

**Comment by tomchentw** [comment]
Released [v2.8.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.8.0)

**Comment by tomchentw** [comment]
@RangarajKaushikSundar invited!

**Pull request merged**
