### PR TITLE
Combines mikecousins pull request and also fixes React.createClass deprecation

### PR DESCRIPTION
**Pull request by martinhoefling**

### CODE REVIEW

**Comment by mikecousins** [comment]
I like it

**Comment by bunkscene** [comment]
We need to get this fix in there!  The warnings in my app are driving me crazy.  How can we get it in there?

**Comment by mikecousins** [comment]
It seems like Tom has died so I forked this and released a new package called react-toastr2.

https://www.npmjs.com/package/react-toastr2
https://github.com/mikecousins/react-toastr

**Comment by bruce** [comment]
Tom appears to still be alive, seeing other activity. I think a fork is cool, but the joke's (?) really not, no matter how frustrated people might be about this project.

**Comment by mikecousins** [comment]
Apologies for the crude joke. I have attempted to contact him through many means over the course of many months. He is clearly not interested in maintaining this package anymore.

**Comment by tomchentw** [comment]
Released [v2.9.0](https://github.com/tomchentw/react-toastr/releases/tag/v2.9.0)

**Pull request closed without merging**
